### ISSUE TITLE
Project Files are missing and create requirements.txt

### ISSUE THREAD

**Issue by dmdhrumilmistry** [priyanka-p01/Hotel-Management-System#1]
You haven't uploaded project files yet and create a requirements.txt / setup file to make installation easy and user friendly.

**Comment by priyanka-p01** [comment]
I am still in the process of updating this project with few things. but you could go ahead and contribute for now :)
[assigned for creating requirements part, if u wish]

> You haven't uploaded project files yet and create a requirements.txt / setup file to make installation easy and user friendly.

**Comment by dmdhrumilmistry** [comment]
Okay, I might pull request in future, you can use DB to authenticate user, if i close the login box, its providing me access without any authentication.

**Comment by priyanka-p01** [comment]
ok cool! ty
